# Example: How to use the security scanner from a consumer repository

name: 'aa Monorepo Code Scanner Inputs'

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:


jobs:
  security-scan:
    uses: MetaMask/experimental-security-codescanner-monorepo/.github/workflows/security-scan.yml@monorepo
    with:
      repo: ${{  github.repository }}
      # languages_config: '' # Leave empty for auto-detection with repo defaults
      # Example with custom Java build:
      languages_config: |
        [
          {
            "language": "java-kotlin",
            "build_mode": "manual",
            "build_command": "./gradlew :coordinator:app:build",
            "version": "21",
            "distribution": "temurin"
          },
          {
            "language": "cpp",
            "ignore": true
          }
        ]
      paths_ignored: |
        
        .storybook/
        **/__snapshots__/
        **/*.snap
        **/*.stories.js
        **/*.test.js*
        **/*.test.ts*
        **/fixtures/
        **/mocks/
        **/test*/
        docs/
        node_modules
        dist
        build
      rules_excluded: |
        rule1
        rule2
      # project_metrics_token: ${{ secrets.SECURITY_SCAN_METRICS_TOKEN }}
      # slack_webhook: ${{ secrets.APPSEC_BOT_SLACK_WEBHOOK }}
    permissions:
      actions: read
      contents: read
      security-events: write